language: go

go:
 - 1.14.x
 - master

script:
 - go test ./...

notifications:
 email: false

before_install:
 - go get gonum.org/v1/gonum/floats
 - go get gonum.org/v1/gonum/optimize
 - go get github.com/kshedden/statmodel/statmodel
 - go get github.com/kshedden/statmodel/glm

